name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          pip install ruff mypy types-all

    - name: Run Ruff formatting
      run: ruff format .

    - name: Run Ruff linting with fix
      run: ruff check . --fix

    - name: Run Mypy (type checking)
      run: mypy insightvault

    - name: Run Pytest (tests)
      run: pytest --doctest-modules --junitxml=junit/test-results.xml

    - name: Upload Test Results for GitHub UI
      uses: actions/upload-test-results@v2
      with:
        path: junit/test-results.xml
